DROP TABLE DEPENDIENTE CASCADE CONSTRAINT;
DROP TABLE ASEGURADO CASCADE CONSTRAINT;
DROP TABLE MUNICIPIO CASCADE CONSTRAINT;
DROP TABLE ESTADO CASCADE CONSTRAINT;

CREATE TABLE ESTADO(
    CLAVE VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    CONSTRAINT EST_CLAVE_PK PRIMARY KEY(CLAVE));

CREATE TABLE MUNICIPIO(
    CLAVE VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    ESTCLAVE VARCHAR(20) NOT NULL,
    CONSTRAINT MUN_CLAVE_PK PRIMARY KEY(CLAVE),
    CONSTRAINT MUN_ESCLAV_FK FOREIGN KEY(ESTCLAVE) REFERENCES ESTADO (CLAVE));

CREATE TABLE ASEGURADO(
    NSS VARCHAR(15) PRIMARY KEY,
    NRP VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    CURP VARCHAR(20) NOT NULL,
    SALARIO FLOAT(7,2) NOT NULL,
    FECHA DATE NOT NULL,
    UBICACION VARCHAR(80) NOT NULL,
    SEXO VARCHAR(2) NOT NULL,
    ENFERMEDAD VARCHAR(40) NOT NULL,
    EDAD INT(3) NOT NULL,
    ESTCLAVE VARCHAR(20) NOT NULL,
    MUNCLAVE VARCHAR(20) NOT NULL
);
ALTER TABLE ASEGURADO ADD CONSTRAINT ASE_ESCLAV_FK FOREIGN KEY(ESTCLAVE) REFERENCES ESTADO (CLAVE);
ALTER TABLE ASEGURADO ADD CONSTRAINT ASE_MUNCLAV_FK FOREIGN KEY(MUNCLAVE) REFERENCES MUNICIPIO (CLAVE);

CREATE TABLE DEPENDIENTE(
    NSS VARCHAR(15) PRIMARY KEY,
    CURP VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    SEXO VARCHAR(2) NOT NULL,
    FECHA_ALT DATE NOT NULL,
    ENFERMEDAD VARCHAR(40) NOT NULL,
    EDAD INT(3) NOT NULL,
    ASE_NSS VARCHAR(15) NOT NULL
);

ALTER TABLE DEPENDIENTE ADD CONSTRAINT DEP_ASE_NSS_FK FOREIGN KEY(ASE_NSS) REFERENCES ASEGURADO(NSS);

